workspace: 
  base: /srv/drone/golang
  path: .
pipeline:
  build:
    image: golang:alpine
    commands:
      - pwd
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
  test:
    image: golang:${GO_VERSION}
    commands:
      - ./app
  matrix:
    GO_VERSION: [alpine, 1.11-alpine3.9]