workspace: 
  base: /srv/drone/golang
  path: src
pipeline:
  build:
    image: golang:alpine
    commands:
      - pwd
      - mkdir ../bin
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ../bin/app .
    volumes:
      - E:\docker\golang\bin:/srv/drone/golang/bin
  test:
    image: alpine
    commands:
      - ../bin/app

branches: master