workspace: 
  base: /srv/drone/golang
  path: src
pipeline:
  build:
    image: golang:alpine
    commands:
      - pwd
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bin/app src/
  test:
    image: alpine
    commands:
      - ./app

branches: master